name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    env:
      python-version: "3.10.x"
      pg-version: "14"
      redis-version: "6.2"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ env.pg-version }}
          postgresql db: casepro
          postgresql user: casepro
          postgresql password: nyaruka

      - name: Install Redis
        uses: zhulik/redis-action@v1.0.0
        with:
          redis version: ${{ env.redis-version }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Initialize environment
        run: |
          poetry install
          npm install
          sudo npm install -g coffee-script less
          ln -s ${{ github.workspace }}/casepro/settings.py.dev ${{ github.workspace }}/casepro/settings.py

      - name: Run pre-test checks
        run: |
          sudo apt-get install gettext
          poetry run ./code_check.py --debug

      - name: Run tests
        run: |
          poetry run coverage run manage.py test --verbosity=2 --noinput
          poetry run coverage xml

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
