apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-casepro-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  DJANGO_SUPERUSER_EMAIL: {{ .Values.secrets.DJANGO_SUPERUSER_EMAIL | quote }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.secrets.DJANGO_SUPERUSER_USERNAME  | quote }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER  | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD  | quote }}
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | quote }}
